---
- name: Installing tomcat9 and tomcat9-admin
  apt:
   name: "{{item.a}}"
   state: "{{item.b}}"
   update_cache: "{{item.c}}"  
  with_items:
   - {a: "{{pckg1}}",b: "{{state1}}",c: "{{cache1}}"}
   - {a: "{{pckg2}}",b: "{{state1}}",c: "{{cache2}}"}
...

